<?php
/**
 * Yireo AdminPreviousNext for Magento 
 *
 * @package     Yireo_AdminPreviousNext
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2014 Yireo (http://www.yireo.com/)
 * @license     Open Source License
 */

$previous = $this->getPrevious();
?>
<script>
<?php if(!empty($previous)) : ?>
var previousHtml = '<button type="button" class="back" '
    + 'title="<?php echo $previous->getName(); ?>" '
    + 'onclick="setLocation(\'<?php echo $previous->getUrl(); ?>\');">'
    + '<span><span><span><?php echo $previous->getLabel(); ?></span></span></span>'
    + '</button>';
jQuery('p.form-buttons').append(previousHtml);
<?php endif; ?>
</script>
