<?php
/**
 * Yireo AdminPreviousNext for Magento 
 *
 * @package     Yireo_AdminPreviousNext
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2014 Yireo (http://www.yireo.com/)
 * @license     Open Source License
 */
?>
<script>
    var yireoDomtastic = $.noConflict();
</script>

<?php
echo $this->getChildHtml('adminpreviousnext.previous');
echo $this->getChildHtml('adminpreviousnext.next');
?>
